export const REQUEST_BAND_CREATION = "REQUEST_BAND_CREATION";
export const CREATE_BAND = "CREATE_BAND";

export const REQUEST_MODIFY_BAND_SCORE = "REQUEST_MODIFY_BAND_SCORE";
export const MODIFY_BAND_SCORE = "MODIFY_BAND_SCORE";

export const REQUEST_AUTHENTICATE_USER = "REQUEST_AUTHENTICATE_USER";
export const PROCESSING_AUTHENTICATE_USER = "PROCESSING_AUTHENTICATE_USER";

export const AUTHENTICATING = "AUTHENTICATING";
export const AUTHENTICATED = "AUTHENTICATED";
export const NOT_AUTHENTICATED = "NOT_AUTHENTICATED";

export const FETCH_BANDS_BEGIN = "FETCH_BANDS_BEGIN";
export const FETCH_BANDS_SUCCESS = "FETCH_BANDS_SUCCESS";
export const FETCH_BANDS_FAILURE = "FETCH_BANDS_FAILURE";

export const SET_STATE = "SET_STATE";