export const AUTHENTICATE_USER_BEGIN = "AUTHENTICATE_USER_BEGIN";
export const AUTHENTICATE_USER_SUCCESS = "AUTHENTICATE_USER_SUCCESS";
export const AUTHENTICATE_USER_FAILURE = "AUTHENTICATE_USER_FAILURE";

export const AuthenticationStatuses = {
    AUTHENTICATING: "AUTHENTICATING",
    AUTHENTICATED: "AUTHENTICATED",
    NOT_AUTHENTICATED: "NOT_AUTHENTICATED"
}

export const FETCH_BANDS_BEGIN = "FETCH_BANDS_BEGIN";
export const FETCH_BANDS_SUCCESS = "FETCH_BANDS_SUCCESS";
export const FETCH_BANDS_FAILURE = "FETCH_BANDS_FAILURE";

export const MODIFY_BAND_SCORE_BEGIN = "MODIFY_BAND_SCORE_BEGIN";
export const MODIFY_BAND_SCORE_SUCCESS = "MODIFY_BAND_SCORE_SUCCESS";
export const MODIFY_BAND_SCORE_FAILURE = "MODIFY_BAND_SCORE_FAILURE";

export const CREATE_BAND_BEGIN = "CREATE_BAND_BEGIN";
export const CREATE_BAND_SUCCESS = "CREATE_BAND_SUCCESS";
export const CREATE_BAND_FAILURE = "CREATE_BAND_FAILURE";

export const SET_STATE = "SET_STATE";